server:
  port: 8080

eureka:
  instance:
    hostname: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: productservice
          uri: http://localhost:8081/
          predicates:
            - Path=/products/**
        - id: cartservice
          uri: http://localhost:8082/
          predicates:
            - Path=/cart/**
        - id: reviewservice
          uri: http://localhost:8083/
          predicates:
            - Path=/reviews/**


# Actuator
info:
  app:
    name: "This is an api gateway"
    version: "1.0.0"
    description: "Centralized login for processing all requests."

management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true